site:
  baseline: Je suis Maxime Pereira-Lima et ceci est mon réceptacle virtuel.
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Europe/Paris
  description: 'Développeur Web, mobile & audiophile.'
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Hello ici ou là.
theme: hyde
